apiVersion: batch/v1
kind: Job
metadata:
  name: laravel-migrate
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: shudd/shortie:0.1-live
          command: ["php", "artisan", "migrate", "--force", "--no-interaction"]
          env:
            - name: DB_CONNECTION
              value: sqlite
            # secrets here

